# Base image
FROM node:16.18.0 AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Set the port
EXPOSE 8000

# Npm run build 
RUN npx prisma generate

Run npm run build

# Start the app
CMD ["npm", "start"]

