# Base image
FROM node:16.18.0 AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Set the port
EXPOSE 8000

# Start the app
CMD ["npm", "start"]

