version: '3.9'

services:

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.next
      args:
        NEXT_PUBLIC_BUILDING_IMAGE: "true"
    ports:
      - '3000:3000'
    env_file:
      - ./client/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.express
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx  
    ports:
      - '80:80'
    depends_on:
      - frontend
