# Dockerfile.next

FROM node:16.18.0 AS build

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY . .

# Build the Next.js application
Run npx prisma generate 

ARG NEXT_PUBLIC_BUILDING_IMAGE

ENV NEXT_PUBLIC_BUILDING_IMAGE=$NEXT_PUBLIC_BUILDING_IMAGE

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
